model:
  base_learning_rate: 1e-5   # ori: 5e-5
  target: ldm.models.unet.UNetLightning
  params:
    model_type: "TransUNet"
    learning_rate: 1e-4
    monitor: 'val/val_iou'
    in_channels: 1
    out_channels: 3
    transunet_variant: "R50-ViT-B_16" # or "ViT-B_16"
    loss_name: dice_ce
    use_poly_lr: False
    poly_lr_power: 0.9
    
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 4
    wrap: True
    cache: True
    cache_rate: 1.0
    use_weighted_sampler: True
    train:
      target: ldm.data.stroke.StrokeTrain
      params:
        size: 256
        include_background: False
        data_root: "dataset/stroke2021/"
        split_files: "dataset/stroke2021/splits.json"
        val_ratio: 0.2
        random_seed: 42
        fold: 0
        num_folds: 5
        expand_image_channel: False
        augmentation: True
    validation:
      target: ldm.data.stroke.StrokeValidation
      params:
        size: 256
        include_background: False
        data_root: "dataset/stroke2021/"
        split_files: "dataset/stroke2021/splits.json"
        val_ratio: 0.2
        random_seed: 42
        fold: 0
        num_folds: 5
        expand_image_channel: False
    test:
      target: ldm.data.stroke.StrokeTest
      params:
        size: 256
        include_background: False
        data_root: "dataset/stroke2021/"
        expand_image_channel: False

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 8
        clamp: False
        rescale: False
        increase_log_steps: False
    early_stopping:
      target: pytorch_lightning.callbacks.EarlyStopping
      params:
        monitor: "val/val_iou"    # izleyecek metrik
        mode: "max"               # IoU yüksek iyi
        patience: 50              # 50 epoch iyileşme yoksa dur
        min_delta: 0.0000         # iyileşme eşiği (istersen 0 yap)
        verbose: True

  trainer:
    benchmark: True
    check_val_every_n_epoch: 1
    accumulate_grad_batches: 1