model:
  base_learning_rate: 1e-5   # ori: 5e-5
  target: ldm.models.unet.UNetLightning
  params:
    model_type: "FlexibleUNet"
    learning_rate: 1e-4
    monitor: 'val/val_iou'
    in_channels: 1
    out_channels: 3
    decoder_channels: [256, 128, 64, 32, 16]
    spatial_dims: 2
    backbone: resnet34
    pretrained: False
    
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 4
    wrap: True
    cache: True
    cache_rate: 1.0
    train:
      target: ldm.data.stroke.StrokeTrain
      params:
        size: 256
        include_background: False
        data_root: "dataset/stroke2021/"
        val_ratio: 0.1
        test_ratio: 0.1
        expand_image_channel: False
        augmentation: True
    validation:
      target: ldm.data.stroke.StrokeValidation
      params:
        size: 256
        include_background: False
        data_root: "dataset/stroke2021/"
        val_ratio: 0.1
        test_ratio: 0.1
        expand_image_channel: False
    test:
      target: ldm.data.stroke.StrokeTest
      params:
        size: 256
        include_background: False
        data_root: "dataset/stroke2021/"
        val_ratio: 0.1
        test_ratio: 0.1
        expand_image_channel: False

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        clamp: False
        rescale: False
        increase_log_steps: False

  trainer:
    benchmark: True
    check_val_every_n_epoch: 1
    accumulate_grad_batches: 1